import React, { useEffect, useState } from 'react';

import dynamic from 'next/dynamic';
import type { NextPage } from 'next';
import Head from 'next/head';

import styles from '../styles/Home.module.scss';

const ButtonBase = dynamic(() => import('../components/ButtonBase'));
const DynamicHeader = dynamic(() => import('../components/DynamicHeader'));

const Home: NextPage = () => {
  const [show, setShowButton] = useState(false);

  useEffect(() => {
    setTimeout(() => setShowButton(true), 1000);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <header>{show && <DynamicHeader />}</header>

      <main className={styles.main}>
        <ButtonBase buttonStyle='blue' className={styles.homeButton}>
          blue button
        </ButtonBase>
      </main>
    </div>
  );
};

export default Home;
