import React, { useEffect, useState } from 'react';

import dynamic from 'next/dynamic';
import type { NextPage } from 'next';
import Head from 'next/head';

import styles from '../styles/Home.module.scss';

const ButtonBase = dynamic(() => import('../components/ButtonBase'));

const Home: NextPage = () => {
  const [showButton, setShowButton] = useState(false);

  useEffect(() => {
    setTimeout(() => setShowButton(true), 3000);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <ButtonBase blue>blue button </ButtonBase>
        {showButton && <ButtonBase>red button</ButtonBase>}
      </main>
    </div>
  );
};

export default Home;
